# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lead_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip',
            field=models.GenericIPAddressField(default='192.168.51.11', unpack_ipv4=True),
            preserve_default=False,
        ),
    ]
